using System;
using System.Collections.Generic;
using interfas;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace interfas
{
  
    public class Bird 
    {
        public void Walk()
        {
          
            Console.WriteLine("Bird is hopping around and flying short distances.");
        }

        public void Eat()
        {
            Console.WriteLine("Bird is pecking seeds.");
        }

        public void Sleep()
        {
            Console.WriteLine("Bird is sleeping on a branch.");
        }

        
        public void MakeSound()
        {
            Console.WriteLine("Tweet! Chirp! (Sings a melody)");
        }
    }
}
class BIRD
    {
    }

