using System;
using System.Collections.Generic;
using interfas;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace interfas
{
    public class dog 
    {
        public void walk()
        {
            Console.WriteLine("dog is trotting happily on four legs");
        }
        public void Eat()
        {
            Console.WriteLine("dog is quickly crunching kibble");
        }
        public void Sleep()
        {
            Console.WriteLine("dog is curled up sleeping soundly,occasionally twitching");
        }
        public void Makesound()
        {
            Console.WriteLine("woof! woof! (barks loudly)");
        }
        class DOG
    {
    }
   
    }
}
